speech_recognition_languages = {
    "English (US)": "en-US",
    "English (UK)": "en-GB",
    "Spanish (Spain)": "es-ES",
    "Spanish (Latin America)": "es-MX",
    "French (France)": "fr-FR",
    "French (Canada)": "fr-CA",
    "German": "de-DE",
    "Italian": "it-IT",
    "Chinese (Mandarin)": "zh-CN",
    "Chinese (Cantonese)": "zh-HK",
    "Japanese": "ja-JP",
    "Korean": "ko-KR",
    "Russian": "ru-RU",
    "Portuguese (Portugal)": "pt-PT",
    "Portuguese (Brazil)": "pt-BR",
    "Arabic (Modern Standard)": "ar-SA",
    "Dutch": "nl-NL",
    "Turkish": "tr-TR",
    "Hindi": "hi-IN",
    "Bengali": "bn-BD",
    "Vietnamese": "vi-VN",
    "Thai": "th-TH",
    "Swedish": "sv-SE",
    "Danish": "da-DK",
    "Finnish": "fi-FI",
    "Norwegian": "no-NO",
    "Greek": "el-GR",
    "Hungarian": "hu-HU",
    "Hebrew": "he-IL",
}